export const STORE_ALL_STOCKS = "STORE_ALL_STOCKS";

export const FILTER_STOCKS = "FILTER_STOCKS";
export const RESET_FILTER = "RESET_FILTER";

export const RESET_FOUND_STOCK = "RESET_FOUND_STOCK";
export const FIND_STOCK_IN_SELECTED = "FIND_STOCK_IN_SELECTED";
export const ADD_OR_EDIT_STOCK_TO_SELECTED = "ADD_OR_EDIT_STOCK_TO_SELECTED";